services:
  ia_trainer:
    build:
      context: .
      dockerfile: Dockerfile.ml
    container_name: ml_trainer
    volumes:
      - ./Datos:/workspace/Datos:z
      - ./Scripts:/workspace/Scripts:z
      - ./Modelos:/workspace/Modelos:z
      - ./Codigo_Fuente/backend/app/ml:/workspace/ml_libs:z
    command: ["sleep", "infinity"]